openapi: 3.0.3
info:
  title: Microservice Template
  description: Microservice Template
  version: 1.0.0
servers:
  - url: '/api/geodata'

components:
  parameters:
    LayerID:
      in: path
      name: layer-id
      description: The UUID for the layer
  schemas:
    Object:
      type: object
      properties:
        id:
          type: integer
          description: database-generated
        name:
          type: string
        key:
          type: string
          description: |
            identifies an object in requests as it is specific to the layer and
            the key definition
        additionalProperties:
          additionalProperties: true
        geometry:
          type: object
          description: A GeoJSON representation of the objects geometry
    Layer:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        description:
          type: string
        crs:
          type: integer
          title: Coordinate Reference System
          description: |
            The EPSG code for the coordinate reference system used in the layer
paths:
  /:
    get:
      summary: Retrieve available Layers
      responses:
        200:
          description: Layers
          content:
            application/json:
              schema:
                type: array
                items:
                  - $ref: '#/components/schemas/Layer'
        204:
          description: No layers available
  /{layer-id}:
    parameters:
      - $ref: '#/components/parameters/LayerID'
    get:
      summary: Get layer information
      responses:
        200:
          description: Layer Information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Layer'
  /content/{layer-id}:
    parameters:
      - $ref: '#/components/parameters/LayerID'
    get:
      summary: Layer Contents
      responses:
        200:
          description: The layers contents
          content:
            application/json:
              schema:
                type: array
                description: |
                  An array containing the single entries of the layer 
                  represented in GeoJSON.
                  Due to the possibility of mixed entries in a layer no actual
                  information is available on a single entry of this response.
                items:
                  $ref: "#/components/schemas/Object"
  /content/{layer-id}/filtered:
    parameters:
      - $ref: '#/components/parameters/LayerID'
    post:
      requestBody:
        content:
          application/json:
            schema:
              example:
                filterName:
                  00000000-0000-0000-0000-000000000000:
                    - "key1"
                    - "key2"
                    - "key3"
                    - "key4"
              additionalProperties:
                additionalProperties:
                  type: array
                  items:
                    type: string
      summary: Filtered Layer Contents
      externalDocs:
        url: https://postgis.net/docs/reference.html#idm12722
      description: |
        This endpoint allows filtering the contents of the given layer (set by
        layer-id) against different geospatial relations.
        Currently the service supports the following geospatial relations:
          * `contains`
          * `overlaps`
          * `within`
        
        These functions all use the names as they are used in the PostGIS
        extension to allow a consistent usage throughout the service
      responses:
        200:
          description: The layers contents
          content:
            application/json:
              schema:
                type: array
                description: |
                  An array containing the single entries of the layer 
                  represented in GeoJSON.
                  Due to the possibility of mixed entries in a layer no actual
                  information is available on a single entry of this response.
                items:
                  $ref: "#/components/schemas/Object"